DemoMVC/Controllers/MonHocController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using DemoMVC.Models;

namespace DemoMVC.Controllers
{
    public class MonHocController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult TinhDiem(MonHocModels model)
        {
            // Tính điểm tổng
            model.DiemTong = model.DiemA * 0.6f + model.DiemB * 0.3f + model.DiemC * 0.1f;

            // Đánh giá kết quả
            if (model.DiemTong >= 8)
            {
                model.KetQua = "Giỏi";
            }
            else if (model.DiemTong >= 6.5)
            {
                model.KetQua = "Khá";
            }
            else if (model.DiemTong >= 5)
            {
                model.KetQua = "Trung bình";
            }
            else
            {
                model.KetQua = "Trượt";
            }

            // Gửi thông báo về View
            ViewBag.ThongBao = "Điểm tổng của môn " + model.TenMonHoc + " là: " + model.DiemTong + ", " + model.KetQua;

            return View("Index");
        }
    }
}

DemoMVC/Views/MonHoc/index.cshtml
@model DemoMVC.Models.MonHocModels

<h2>Tính điểm môn học</h2>

@using (Html.BeginForm("TinhDiem", "MonHoc", FormMethod.Post))
{
    @Html.LabelFor(m => m.TenMonHoc, "Tên môn học:")
    @Html.TextBoxFor(m => m.TenMonHoc)
    <br />

    @Html.LabelFor(m => m.DiemA, "Điểm A:")
    @Html.TextBoxFor(m => m.DiemA)
    <br />

    @Html.LabelFor(m => m.DiemB, "Điểm B:")
    @Html.TextBoxFor(m => m.DiemB)
    <br />

    @Html.LabelFor(m => m.DiemC, "Điểm C:")
    @Html.TextBoxFor(m => m.DiemC)
    <br />

    <button type="submit">Tính</button>
}

@if (ViewBag.ThongBao != null)
{
    <p>@ViewBag.ThongBao</p>
}