DemoMVC/Models/HoaDon.cs
using System.ComponentModel.DataAnnotations;

namespace DemoMVC.Models
{
    public class HoaDonModel
    {
        public string TenHang { get; set; }= string.Empty;
        public int SoLuong { get; set; }
        public float DonGia { get; set; }
        public float ThanhTien { get; set; }
    }
}

DemoMVC/Controllers/HoaDonController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using DemoMVC.Models;

namespace DemoMVC.Controllers
{
    public class HoaDonController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult TinhTien(HoaDonModel model)
        {
            // Tính thành tiền
            model.ThanhTien = model.SoLuong * model.DonGia;

            // Gửi thông báo về View
            ViewBag.ThongBao = "Thành tiền của mặt hàng " + model.TenHang + " là: " + model.ThanhTien;

            return View("Index");
        }
    }
}

DemoMVC/Views/HoaDon/index.cshtml
@model DemoMVC.Models.HoaDonModel

<h2>Tính tiền hóa đơn</h2>

@using (Html.BeginForm("TinhTien", "HoaDon", FormMethod.Post))
{
    @Html.LabelFor(m => m.TenHang, "Tên hàng:")
    @Html.TextBoxFor(m => m.TenHang)
    <br />

    @Html.LabelFor(m => m.SoLuong, "Số lượng:")
    @Html.TextBoxFor(m => m.SoLuong)
    <br />

    @Html.LabelFor(m => m.DonGia, "Đơn giá:")
    @Html.TextBoxFor(m => m.DonGia)
    <br />

    <button type="submit">Tính</button>
}

@if (ViewBag.ThongBao != null)
{
    <p>@ViewBag.ThongBao</p>
}